### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by n1rw4n** [yii2tech/html2pdf#1]
hi,

i am getting error

Unable to convert file 'I:\xx\xx\frontend\runtime\html2pdf\wkh54DA.tmp.html': The filename, directory name, or volume label syntax is incorrect.

`$report=$this->renderPartial('pdf',['objectPrint'=>$result_object]);
Yii::$app->html2pdf
->convert($report)
->saveAs('/path/to/output.pdf');`

**Comment by klimov-paul** [comment]
Unable to reproduce.
