### ISSUE TITLE
why do not display image?  i use xvfb-run wxhtmltopdf

### ISSUE THREAD

**Issue by huaiguoguo** [yii2tech/html2pdf#10]
why do not display image?  i use xvfb-run wxhtmltopdf

![image](https://user-images.githubusercontent.com/1888094/38148779-6b11936a-348a-11e8-9f95-7865e2b838c6.png)

![image](https://user-images.githubusercontent.com/1888094/38148685-148cdbbc-348a-11e8-8f24-bbd2b7237cdd.png)

![image](https://user-images.githubusercontent.com/1888094/38148658-fa802616-3489-11e8-8025-70a505330a10.png)

**Comment by klimov-paul** [comment]
I can not say.
If you have problems with `wkhtmltopdf` command you should report it to http://wkhtmltopdf.org/
