### ISSUE TITLE
Exit with code 1 due to network error: ContentNotFoundError

### ISSUE THREAD

**Issue by mwaigichuhi** [yii2tech/html2pdf#13]
I get this exception when trying the second example below:

```
Yii::$app->html2pdf
    ->render('invoice', ['user' => Yii::$app->user->identity])
    ->saveAs('/path/to/output.pdf');
```

### Exception – yii\base\Exception
Unable to convert file '/var/www/yii2-project/runtime/html2pdf/wkhtmltopdfT3fSRk.html': Loading pages (1/6)
[> ] 0%
[======> ] 10%
[======> ] 10%
[============================================================] 100%
Counting pages (2/6)
[============================================================] Object 1 of 1
Resolving links (4/6)
[============================================================] Object 1 of 1
Loading headers and footers (5/6)
Printing pages (6/6)
[> ] Preparing
[============================================================] Page 1 of 1
Done
Exit with code 1 due to network error: ContentNotFoundError

**Comment by klimov-paul** [comment]
Unable to reproduce, following unit test passes correctly:

```php
public function testRenderWkhtmltopdf()
    {
        $manager = new Manager([
            'viewPath' => __DIR__ . '/data/views',
            'layout' => 'layout',
            'converter' => [
                'class' => Wkhtmltopdf::className()
            ],
        ]);;

        $file = $manager->render('simple', ['testParam' => 'foo']);

        $filename = Yii::getAlias('@runtime/output.pdf');
        $file->saveAs($filename);

        $this->assertTrue(file_exists($filename));
        $fileContent = file_get_contents($filename);
        $this->assertNotEmpty($fileContent);
    }
```
