### ISSUE TITLE
Svg Graph to pdf

### ISSUE THREAD

**Issue by mrabd423** [yii2tech/html2pdf#2]
hello, I have a webpage in which table and some other information is there. But i've a Radar graph of fusion charts. So graph is rendered in SVG. Will this api convert the graph into pdf too or not ?
![pp-step-9](https://user-images.githubusercontent.com/13703122/30908545-4f5b2ba6-a397-11e7-9805-27360546d63d.png)

**Comment by klimov-paul** [comment]
No idea. This depends on particular PDF convertor library you are using.

**Comment by mrabd423** [comment]
What if i will use yii2tech/html2pdf

**Comment by klimov-paul** [comment]
This extension does NOT perform conversion on its own! It uses 3rd part library, which **you** have to choose.
