### ISSUE TITLE
Feature Request: extend Manager to support cli arguments

### ISSUE THREAD

**Issue by IVoyt** [yii2tech/html2pdf#22]
### What steps will reproduce the problem?
Generate pdf

### What is the expected result?
Get generated pdf

### What do you get instead?
Exception

### Additional info
html2pdf - 1.0.7
Yii2 - 2.0.40-dev
PDF Converter - wkhtmltopdf
PDF Converter Version - 0.12.x
PHP - 7.2 - 7.4
OS - Centos 6, Ubuntu 20

To avoid "Unable to write to destination" or "Block access to file ..." errors, please extend Manager to support cli arguments, which fix these issues.
Arguments are:
--enable-local-file-access
--disable-local-file-access
--allow <path>

Reference: https://stackoverflow.com/questions/62315246/wkhtmltopdf-0-12-6-warning-blocked-access-to-file

**Comment by klimov-paul** [comment]
Any cli argument for `wkhtmltopdf` can be set via convertor options. In your case:

```php
<?php

return [
    'components' => [
        'html2pdf' => [
            'class' => 'yii2tech\html2pdf\Manager',
            'viewPath' => '@app/pdf',
            'converter' => [
                'class' => 'yii2tech\html2pdf\converters\Wkhtmltopdf',
                'defaultOptions' => [
                    'enableLocalFileAccess' => true
                ],
            ]
        ],
    ],
    // ...
];
```

**Comment by IVoyt** [comment]
Great! Didn't know about this option. Thanks!
