### ISSUE TITLE
wkhtmltopdf is not recognized as an internal or external command

### ISSUE THREAD

**Issue by srakl** [yii2tech/html2pdf#24]
### What steps will reproduce the problem?

in my `main.php`

```
'html2pdf' => [
            'class' => 'yii2tech\html2pdf\Manager',
            //'viewPath' => '@app/views/pdf',
            'converter' => [
                'class' => 'yii2tech\html2pdf\converters\Wkhtmltopdf',
                'defaultOptions' => [
                    'pageSize' => 'A4'
                ],
            ]
        ],
```

I installed the windows version here

https://wkhtmltopdf.org/downloads.html

### What do you get instead?

```
Unable to convert file 'C:\xampp\htdocs\yii2\frontend\runtime\html2pdf\wkh3801.tmp.html': 'wkhtmltopdf' is not recognized as an internal or external command,
operable program or batch file.
```

How do i get it to work on my localhost? and once i move my site to my ubuntu server? What am i missing here? Thanks

### Additional info

| Q                     | A
| --------------------- | ---
| This Package Version  | 1.?.?
| Yii Framework Version | 2.0.43
| PDF Converter         | wkhtmltopdf
| PDF Converter Version | ?.?.?
| PHP version           |  8.0.8
| Operating system      | Windows 10

**Comment by srakl** [comment]
Tried using Dompdf too

```
'html2pdf' => [
            'class' => 'yii2tech\html2pdf\Manager',
            'converter' => 'yii2tech\html2pdf\converters\Dompdf', 
        ],
```

installed Dompdf using composer

```
composer require dompdf/dompdf
```

in my controller

```
function actionPdf() {
     $content = '<h1>hi</h1>';
     return Yii::$app->html2pdf->convert($content);
}
```

I get this error

`Response content must be a string or an object implementing __toString()`

**Comment by klimov-paul** [comment]
Sorry, I do not provide the consulting regardless setup of the web server environment. Please seek help elsewhere.
