### ISSUE TITLE
wkhtmltopdf: command not found`

### ISSUE THREAD

**Issue by gh-darvishani** [yii2tech/html2pdf#4]
`Exception – yii\base\Exception
Unable to convert file '/Applications/XAMPP/xamppfiles/htdocs/sahel/backend/runtime/html2pdf/wkhtmltopdfAsG4nc.html': sh: wkhtmltopdf: command not found`

when i want create pdf i get above error .

`$html = <<<HTML
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<p>Simple Content</p>
</body>
</html>
HTML;
Yii::$app->html2pdf
    ->convert($html)
    ->saveAs(base_dir."up/".rand(9,9999).".pdf");`

`  'html2pdf' => [
            'class' => 'yii2tech\html2pdf\Manager',
            'viewPath' => '@app/pdf',
            'converter' => 'wkhtmltopdf',
        ],`

where am i go wrong !

**Comment by apaoww** [comment]
I think you have to install https://wkhtmltopdf.org/downloads.html on whatever machine you working on.
