### ISSUE TITLE
One remark about wkhtmltopdf and options

### ISSUE THREAD

**Issue by Bhoft** [yii2tech/html2pdf#8]
It has taken me **"ages"** to get the cover, headers and footers and toc correctly rendered into the pdf.

The problem was that the order in the command of the option is important!

If the order is something like:
`cover, header-html, footer-html`
The headers and footers wont be rendered

`cover, toc, header-html, footer-html`
The headers and footers will only be on the toc page.

The order is impotent!
The options must be used in that order:
`header-html, footer-html, cover, toc`

To get the cover (which is rendered without header footer), toc (with header footer) and all other pages with header + footer rendered.

I found this here:
https://stackoverflow.com/questions/10583272/wkhtmltopdf-header-on-every-page

maybe it will be good if those options are added to the command manually and not by 
` foreach ($this->normalizeOptions($options) `

At least this is the issue with the windows version `wkhtmltopdf 0.12.4 (with patched qt)`

**Comment by klimov-paul** [comment]
Resolved by commit c137e0135a794cb7c41b8c7381e5b2cc06628c3d
