### ISSUE TITLE
wrong parameter pageSize is documentation for wkhtmltopdf  used

### ISSUE THREAD

**Issue by Bhoft** [yii2tech/html2pdf#9]
After the documentation https://wkhtmltopdf.org/usage/wkhtmltopdf.txt
and the manual printed by -h option.

The parameter is `page-size` not `pageSize` as it is used in the readme
https://github.com/yii2tech/html2pdf/blob/master/README.md

if the same "defaultOptions" should be used regarding if the converter is mpdf or wkhtmltopdf then it must be replaced for wkhtmltopdf.

Anyhow the given examples sets pageSize for the wkhtmltopdf  which is not correct.

**Comment by klimov-paul** [comment]
Unable to reproduce: option 'pageSize' is recognized correctly.
Following unit test passes:

```php
public function testPageSize()
{
    $converter = new Wkhtmltopdf();

    $sourceFileName = dirname(__DIR__) . '/data/html/simple.html';
    $outputA4FileName = $this->ensureTestFilePath() . '/output-a4.pdf';
    $outputA3FileName = $this->ensureTestFilePath() . '/output-a3.pdf';

    $converter->convert(file_get_contents($sourceFileName), $outputA4FileName, ['pageSize' => 'A4']);
    $converter->convert(file_get_contents($sourceFileName), $outputA3FileName, ['pageSize' => 'A3']);

    $this->assertTrue(filesize($outputA3FileName) > filesize($outputA4FileName));
}
```

Camel case options converted to console ones at [normalizeOptions()](https://github.com/yii2tech/html2pdf/blob/master/src/converters/Wkhtmltopdf.php#L103).

**Comment by Bhoft** [comment]
Thanks you are right ;)
i haven't seen that all options are converted when i was going through each possible option from the wkhtmltopdf documention and comparing it with the option names in the example.
